version: "3.8"
services:
  bgptotals:
    build: ./container-files/bgp_api/.
    container_name: bgptotals
    ports:
      - 8000:8000
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    privileged: true
    volumes:
      - ./container-files/grafana:/var/lib/grafana
    ports:
      - 3000:3000
  influxdb:
    image: influxdb:latest 
    volumes:
      - ./container-files/influxdb:/var/lib/influxdb
    container_name: influxdb
    # ports:
    #  - 8086:8086
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./container-files/telegraf/bgp_totals:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    # ports:
    #  - 8125:8125
    #  - 8092:8092/udp
    #  - 8094:8094
    links:
      - bgptotals
      - influxdb
    depends_on:
      - influxdb
      - bgptotals
